export const defBus = [
  {
    gsx$name: "אביטל הפקות",
    gsx$address: "כרמל 32",
    gsx$city: "נוף הגליל",
    gsx$email: "avitalprod@gmail.com",
    gsx$phone: ["0547421862", "0506903932", undefined],
    gsx$worktime: [`יום א-ה: 08:00 - 22:00`, `יום ו: 08:00 - 15:00`, `יום שבת - סגור`],
    gsx$facebook: "https://www.facebook.com/Avital.Productions/",
    gsx$instagram: "https://www.instagram.com/avital_pro/",
    gsx$whatsapp: "0547421862",
    gsx$desc: "הפקת חתונות, בר-מצוות, ימי הולדת",
    gsx$tags: [],
    gsx$comment: `לא לפנות בשבת`,

  },
  {
    gsx$address: "שומרון 1",
    gsx$addressGeolocation: [null, null],
    gsx$phone: ["0508118216", undefined, undefined],
    gsx$whatsapp: "0508118216",
    gsx$email: `debase@gmail.com`,
    gsx$facebook: "https://facebook.com/TheBassHipHopDance",
    gsx$instagram: "https://instagram.com/thebass.official",
    gsx$website: null,
    gsx$comment: `לא לפנות בשבת`,
    gsx$worktime: [`יום א-ה: 08:00 - 22:00`, `יום ו: 08:00 - 15:00`, `יום שבת - סגור`],
    gsx$tags: [],
    gsx$name: "דה בייס",
    gsx$city: "נוף הגליל",
    gsx$desc:
      'סטודיו "דה בייס" סטודיו מקצועי, הראשון והיחיד בעיר לריקודי רחוב וסגנון ההיפ הופ בפרט, בהנהלת נטלי מלין. מתאים לכל הרמות וכל הגילאים לפי קבוצות החל מכיתה א\' ועד גיל 20+\n',
    gsx$active: true,
    gsx$link: "1",
  },
  {
    gsx$address: null,
    gsx$addressGeolocation: [null, null],
    gsx$phone: ["0508106269", undefined, undefined],
    gsx$whatsapp: "0508106269",
    gsx$email: `ugalona@gmail.com`,
    gsx$facebook: "https://facebook.com/alona1222",
    gsx$instagram: "https://instagram.com/alonanaftt_ugalona",
    gsx$website: "https://bcard.digital/alona",
    gsx$comment: `לא לפנות בשבת`,
    gsx$worktime: [`יום א-ה: 08:00 - 22:00`, `יום ו: 08:00 - 15:00`, `יום שבת - סגור`],
    gsx$tags: [],
    gsx$name: "עוגלונה",
    gsx$city: "נוף הגליל",
    gsx$desc:
      "עוגות בעיצוב אישי * עוגות לכל אירוע * בר מתוקים * עיצוב שולחן מתוקים * עוגות מוס * קאפקייקס * עוגות אישיות * ביצי שוקולד בגדלים שונים * עוגות שמרים * ועוד...",
    gsx$active: true,
    gsx$link: "2",
  },
];
